name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  analyze:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
    - uses: bluefireteam/melos-action@v2
    - run: melos bootstrap
    - run: melos analyze

  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
    - uses: bluefireteam/melos-action@v2
    - run: sudo apt update
    - run: sudo apt install -y clang cmake curl libgtk-3-dev ninja-build pkg-config unzip
      env:
        DEBIAN_FRONTEND: noninteractive
    - run: melos bootstrap
    - run: melos build

  coverage:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
    - uses: bluefireteam/melos-action@v2
    - run: sudo apt update
    - run: sudo apt install -y lcov
      env:
        DEBIAN_FRONTEND: noninteractive
    - run: melos bootstrap
    - run: melos coverage
    - uses: codecov/codecov-action@v3
      with:
        token: ${{secrets.CODECOV_TOKEN}}

  format:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
    - uses: bluefireteam/melos-action@v2
    - run: melos bootstrap
    - run: melos format

  pub:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
    - uses: bluefireteam/melos-action@v2
    - run: melos bootstrap
    - run: melos exec -c 1 --ignore='*example*' -- flutter pub publish --dry-run

  test:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
    - uses: bluefireteam/melos-action@v2
    - run: melos bootstrap
    - run: melos test
